version: 1.0.{build}
os: WMF 5
# Skip on updates to the readme
skip_commits:
  message: /readme*/

install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force

build: false
